[theme]
primaryColor = "#EC4899"
backgroundColor = "#FAFAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = true
fileWatcherType = "none"
maxMessageSize = 500
enableStaticServing = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
