[theme]
primaryColor = "#FF007F"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
fileWatcherType = "none"
maxMessageSize = 200

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
