[theme]
primaryColor = "#FF007F"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false
